// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: service/heart_beat/heart_beat.proto

package heart_beat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartBeatMes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartBeatMes) Reset() {
	*x = HeartBeatMes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_heart_beat_heart_beat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatMes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatMes) ProtoMessage() {}

func (x *HeartBeatMes) ProtoReflect() protoreflect.Message {
	mi := &file_service_heart_beat_heart_beat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatMes.ProtoReflect.Descriptor instead.
func (*HeartBeatMes) Descriptor() ([]byte, []int) {
	return file_service_heart_beat_heart_beat_proto_rawDescGZIP(), []int{0}
}

type HeartBeatMesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mes  string `protobuf:"bytes,1,opt,name=mes,proto3" json:"mes,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *HeartBeatMesRequest) Reset() {
	*x = HeartBeatMesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_heart_beat_heart_beat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatMesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatMesRequest) ProtoMessage() {}

func (x *HeartBeatMesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_heart_beat_heart_beat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatMesRequest.ProtoReflect.Descriptor instead.
func (*HeartBeatMesRequest) Descriptor() ([]byte, []int) {
	return file_service_heart_beat_heart_beat_proto_rawDescGZIP(), []int{0, 0}
}

func (x *HeartBeatMesRequest) GetMes() string {
	if x != nil {
		return x.Mes
	}
	return ""
}

func (x *HeartBeatMesRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type HeartBeatMesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *HeartBeatMesResponse) Reset() {
	*x = HeartBeatMesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_heart_beat_heart_beat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatMesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatMesResponse) ProtoMessage() {}

func (x *HeartBeatMesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_heart_beat_heart_beat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatMesResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatMesResponse) Descriptor() ([]byte, []int) {
	return file_service_heart_beat_heart_beat_proto_rawDescGZIP(), []int{0, 1}
}

func (x *HeartBeatMesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_service_heart_beat_heart_beat_proto protoreflect.FileDescriptor

var file_service_heart_beat_heart_beat_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x5f,
	0x62, 0x65, 0x61, 0x74, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x5f, 0x62, 0x65, 0x61, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x65, 0x61, 0x72, 0x74, 0x5f, 0x62, 0x65, 0x61, 0x74, 0x22,
	0x63, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x1a,
	0x2f, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x1a, 0x22, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x32, 0x7b, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61,
	0x74, 0x12, 0x6e, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x2e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68,
	0x65, 0x61, 0x72, 0x74, 0x5f, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68,
	0x65, 0x61, 0x72, 0x74, 0x5f, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1e, 0x5a, 0x1c, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x5f, 0x62, 0x65, 0x61,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_heart_beat_heart_beat_proto_rawDescOnce sync.Once
	file_service_heart_beat_heart_beat_proto_rawDescData = file_service_heart_beat_heart_beat_proto_rawDesc
)

func file_service_heart_beat_heart_beat_proto_rawDescGZIP() []byte {
	file_service_heart_beat_heart_beat_proto_rawDescOnce.Do(func() {
		file_service_heart_beat_heart_beat_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_heart_beat_heart_beat_proto_rawDescData)
	})
	return file_service_heart_beat_heart_beat_proto_rawDescData
}

var file_service_heart_beat_heart_beat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_heart_beat_heart_beat_proto_goTypes = []interface{}{
	(*HeartBeatMes)(nil),         // 0: proto.service.heart_beat.HeartBeatMes
	(*HeartBeatMesRequest)(nil),  // 1: proto.service.heart_beat.HeartBeatMes.request
	(*HeartBeatMesResponse)(nil), // 2: proto.service.heart_beat.HeartBeatMes.response
}
var file_service_heart_beat_heart_beat_proto_depIdxs = []int32{
	1, // 0: proto.service.heart_beat.HeartBeat.HeartBeat:input_type -> proto.service.heart_beat.HeartBeatMes.request
	2, // 1: proto.service.heart_beat.HeartBeat.HeartBeat:output_type -> proto.service.heart_beat.HeartBeatMes.response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_heart_beat_heart_beat_proto_init() }
func file_service_heart_beat_heart_beat_proto_init() {
	if File_service_heart_beat_heart_beat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_heart_beat_heart_beat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatMes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_heart_beat_heart_beat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatMesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_heart_beat_heart_beat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatMesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_heart_beat_heart_beat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_heart_beat_heart_beat_proto_goTypes,
		DependencyIndexes: file_service_heart_beat_heart_beat_proto_depIdxs,
		MessageInfos:      file_service_heart_beat_heart_beat_proto_msgTypes,
	}.Build()
	File_service_heart_beat_heart_beat_proto = out.File
	file_service_heart_beat_heart_beat_proto_rawDesc = nil
	file_service_heart_beat_heart_beat_proto_goTypes = nil
	file_service_heart_beat_heart_beat_proto_depIdxs = nil
}
